[mypy]
ignore_missing_imports = True
disable_error_code = attr-defined, no-untyped-def, type-arg, var-annotated, return-value, func-returns-value, no-any-return, arg-type, union-attr, index, name-defined, assignment
